from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml
from huggingface_hub import HfApi

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.hf_auth import ensure_hf_token_from_colab


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Push tokenizer artifacts to HF model repo.")
    parser.add_argument(
        "--config",
        type=str,
        default="configs/data.yaml",
        help="Path to config yaml.",
    )
    parser.add_argument(
        "--repo-id",
        type=str,
        default=None,
        help="Override tokenizer repo id (model repo).",
    )
    return parser.parse_args()


def load_config(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)
    loaded = ensure_hf_token_from_colab(cfg)
    if loaded:
        print("[auth] Loaded HF token from Colab key.")

    tok_cfg = cfg.get("tokenization", {})
    push_cfg = cfg.get("hf_tokenizer_push", {})
    repo_id = args.repo_id or push_cfg.get("repo_id")
    private = bool(push_cfg.get("private", False))

    if not repo_id:
        raise ValueError("Tokenizer HF repo_id is missing. Set hf_tokenizer_push.repo_id.")

    tokenizer_dir = Path(tok_cfg.get("output_dir", Path(cfg["output"]["dir"]) / "tokenizer"))
    required_files = [
        tokenizer_dir / "tokenizer.json",
        tokenizer_dir / "tokenizer_meta.json",
        tokenizer_dir / "token_stats.json",
    ]
    missing = [str(p) for p in required_files if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing tokenizer artifacts. Run `python scripts/run_tokenizer.py --config ...` first.\n"
            f"Missing: {missing}"
        )

    api = HfApi()
    api.create_repo(repo_id=repo_id, repo_type="model", private=private, exist_ok=True)

    for path in required_files:
        api.upload_file(
            path_or_fileobj=str(path),
            path_in_repo=path.name,
            repo_id=repo_id,
            repo_type="model",
        )

    # Small README for discoverability in the tokenizer repo.
    readme_text = (
        "# SVG Scaling Tokenizer\n\n"
        "This repository stores tokenizer artifacts generated by `scripts/run_tokenizer.py`.\n\n"
        "Files:\n"
        "- `tokenizer.json`\n"
        "- `tokenizer_meta.json`\n"
        "- `token_stats.json`\n"
    )
    tmp_readme = tokenizer_dir / "HF_TOKENIZER_README.md"
    tmp_readme.write_text(readme_text, encoding="utf-8")
    api.upload_file(
        path_or_fileobj=str(tmp_readme),
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="model",
    )

    print(f"Pushed tokenizer artifacts to: {repo_id}")
    print(json.dumps({"repo_id": repo_id, "repo_type": "model"}, ensure_ascii=False))


if __name__ == "__main__":
    main()
